CREATE OR REPLACE DATABASE letsgetchecked;
CREATE OR REPLACE WAREHOUSE MY_WAREHOUSE;
CREATE OR REPLACE FILE FORMAT MY_FOMRAT TYPE = CSV FIELD_DELIMITER = '|';
CREATE OR REPLACE STAGE MY_STAGE FILE_FORMAT = MY_FOMRAT;