------ METRIC GIVING THE AVERAGE END DAY RATE AND SUM OF AVERAGE RATE -------
SELECT DC.CURRENCYNAME,
       DD.CALENDARYEAR,
       DD.MONTHNUMBEROFYEAR,
       AVG(ENDOFDAYRATE),
       SUM(AVERAGERATE)
  FROM FACTCURRENCYRATE FCR,
       DIMCURRENCY DC,
       DIMDATE DD
 WHERE FCR.CURRENCYKEY = DC.CURRENCYKEY
   AND FCR.DATEKEY = DD.DATEKEY
 GROUP BY DC.CURRENCYNAME,
          DD.CALENDARYEAR,
          DD.MONTHNUMBEROFYEAR;

---- METRIC TO FIND THE THE TOTAL AMOUNT FOR AN ORGANIZATION AND DEPARTMENT IN A GIVEN YEAR -----
SELECT DD.FISCALYEAR,
       DO.ORGANIZATIONNAME,
       DDG.DEPARTMENTGROUPNAME,
       SUM(AMOUNT)
       -- OTHER AGGREGATE METRICS --
  FROM FACTFINANCE FF,
       DIMDATE DD,
       DIMORGANIZATION DO,
       DIMDEPARTMENTGROUP DDG
 WHERE FF.DATEKEY = DD.DATEKEY
   AND FF.ORGANIZATIONKEY = DO.ORGANIZATIONKEY
   AND FF.DEPARTMENTGROUPKEY = DDG.DEPARTMENTGROUPKEY
 GROUP BY DD.FISCALYEAR,
          DO.ORGANIZATIONNAME,
          DDG.DEPARTMENTGROUPNAME;

---- METRIC TO FIND THE TOTAL COST, TOTAL SALES AND DERIVE PROFIT ---------
SELECT SUM(FIS.TOTALPRODUCTCOST),
       SUM(FIS.SALESAMOUNT),
       (SUM(FIS.SALESAMOUNT) - SUM(FIS.TOTALPRODUCTCOST)) AS PROFIT,
       DP.MODELNAME,
       DC.CURRENCYNAME,
       DST.SALESTERRITORYCOUNTRY,
       DOD.CALENDARYEAR,
       DOD.MONTHNUMBEROFYEAR
  FROM FACTINTERNETSALES FIS,
       DIMPRODUCT DP,
       DIMDATE DOD,
       DIMCURRENCY DC,
       DIMSALESTERRITORY DST
 WHERE FIS.PRODUCTKEY = DP.PRODUCTKEY
   AND FIS.CURRENCYKEY = DC.CURRENCYKEY
   AND FIS.SALESTERRITORYKEY = DST.SALESTERRITORYKEY
   AND FIS.ORDERDATEKEY = DOD.DATEKEY
 GROUP BY DP.MODELNAME,
          DC.CURRENCYNAME,
          DST.SALESTERRITORYCOUNTRY,
          DOD.CALENDARYEAR,
          DOD.MONTHNUMBEROFYEAR;

---- A METRIC TO MEASURE THE INVENTORY BALANCE OF A PRODUCT BY YEAR AND MONTH -----
SELECT DP.MODELNAME,
       DD.CALENDARYEAR,
       DD.MONTHNUMBEROFYEAR,
       SUM(UNITSBALANCE)
  FROM FACTPRODUCTINVENTORY FPI,
       DIMPRODUCT DP,
       DIMDATE DD
 WHERE FPI.PRODUCTKEY = DP.PRODUCTKEY
   AND FPI.DATEKEY = DD.DATEKEY
 GROUP BY DP.MODELNAME,
          DD.CALENDARYEAR,
          DD.MONTHNUMBEROFYEAR;

------- METRIC TO FIND THE TOTAL SALES QUOTA USED BY AN EMPLOYEE IN A YEAR
SELECT DE.FIRSTNAME||' '||DE.LASTNAME AS NAME,
       FSQ.CALENDARYEAR,
       SUM(SALESAMOUNTQUOTA)
  FROM FACTSALESQUOTA FSQ,
       DIMEMPLOYEE DE
 WHERE FSQ.EMPLOYEEKEY = DE.EMPLOYEEKEY
 GROUP BY DE.FIRSTNAME||' '||DE.LASTNAME,
          FSQ.CALENDARYEAR;

----- COUNT OF RESPONSE FOR A PRODUCT CATEGORY AND SUB CATEGORY, YEAR AND MONTH WISE AGGREGATED --------
SELECT DD.CALENDARYEAR,
       DD.MONTHNUMBEROFYEAR,
       FSR.ENGLISHPRODUCTCATERYNAME,
       FSR.ENGLISHPRODUCTSUBCATERYNAME,
       COUNT(1)
  FROM FACTSURVEYRESPONSE FSR,
       DIMDATE DD
 WHERE FSR.DATEKEY = DD.DATEKEY
 GROUP BY DD.CALENDARYEAR,
          DD.MONTHNUMBEROFYEAR,
          FSR.ENGLISHPRODUCTCATERYNAME,
          FSR.ENGLISHPRODUCTSUBCATERYNAME;
