CREATE TABLE DIMACCOUNT(
	ACCOUNTKEY INT PRIMARY KEY,
	PARENTACCOUNTKEY INT NULL,
	ACCOUNTCODEALTERNATEKEY INT NULL,
	PARENTACCOUNTCODEALTERNATEKEY INT NULL,
	ACCOUNTDESCRIPTION VARCHAR(50) NULL,
	ACCOUNTTYPE VARCHAR(50) NULL,
	OPERATOR VARCHAR(50) NULL,
	CUSTOMMEMBERS VARCHAR(300) NULL,
	VALUETYPE VARCHAR(50) NULL,
	CUSTOMMEMBEROPTIONS VARCHAR(200) NULL
);


CREATE TABLE DIMCURRENCY(
	CURRENCYKEY INT PRIMARY KEY,
	CURRENCYALTERNATEKEY CHAR(3) NOT NULL,
	CURRENCYNAME VARCHAR(50) NOT NULL
);


CREATE TABLE DIMCUSTOMER(
	CUSTOMERKEY INT PRIMARY KEY,
	GEOGRAPHYKEY INT NULL,
	CUSTOMERALTERNATEKEY VARCHAR(15) NOT NULL,
	TITLE VARCHAR(8) NULL,
	FIRSTNAME VARCHAR(50) NULL,
	MIDDLENAME VARCHAR(50) NULL,
	LASTNAME VARCHAR(50) NULL,
	NAMESTYLE BOOLEAN NULL,
	BIRTHDATE DATE NULL,
	MARITALSTATUS CHAR(1) NULL,
	SUFFIX VARCHAR(10) NULL,
	GENDER VARCHAR(1) NULL,
	EMAILADDRESS VARCHAR(50) NULL,
	YEARLYINCOME DECIMAL(19,4) NULL,
	TOTALCHILDREN TINYINT NULL,
	NUMBERCHILDRENATHOME TINYINT NULL,
	ENGLISHEDUCATION VARCHAR(40) NULL,
	SPANISHEDUCATION VARCHAR(40) NULL,
	FRENCHEDUCATION VARCHAR(40) NULL,
	ENGLISHOCCUPATION VARCHAR(100) NULL,
	SPANISHOCCUPATION VARCHAR(100) NULL,
	FRENCHOCCUPATION VARCHAR(100) NULL,
	HOUSEOWNERFLAG CHAR(1) NULL,
	NUMBERCARSOWNED TINYINT NULL,
	ADDRESSLINE1 VARCHAR(120) NULL,
	ADDRESSLINE2 VARCHAR(120) NULL,
	PHONE VARCHAR(20) NULL,
	DATEFIRSTPURCHASE DATE NULL,
	COMMUTEDISTANCE VARCHAR(15) NULL
);


CREATE TABLE DIMDATE(
	DATEKEY INT NOT NULL,
	FULLDATEALTERNATEKEY DATE NOT NULL,
	DAYNUMBEROFWEEK TINYINT NOT NULL,
	ENGLISHDAYNAMEOFWEEK VARCHAR(10) NOT NULL,
	SPANISHDAYNAMEOFWEEK VARCHAR(10) NOT NULL,
	FRENCHDAYNAMEOFWEEK VARCHAR(10) NOT NULL,
	DAYNUMBEROFMONTH TINYINT NOT NULL,
	DAYNUMBEROFYEAR SMALLINT NOT NULL,
	WEEKNUMBEROFYEAR TINYINT NOT NULL,
	ENGLISHMONTHNAME VARCHAR(10) NOT NULL,
	SPANISHMONTHNAME VARCHAR(10) NOT NULL,
	FRENCHMONTHNAME VARCHAR(10) NOT NULL,
	MONTHNUMBEROFYEAR TINYINT NOT NULL,
	CALENDARQUARTER TINYINT NOT NULL,
	CALENDARYEAR SMALLINT NOT NULL,
	CALENDARSEMESTER TINYINT NOT NULL,
	FISCALQUARTER TINYINT NOT NULL,
	FISCALYEAR SMALLINT NOT NULL,
	FISCALSEMESTER TINYINT NOT NULL
);


CREATE TABLE DIMDEPARTMENTGROUP(
	DEPARTMENTGROUPKEY INT PRIMARY KEY,
	PARENTDEPARTMENTGROUPKEY INT NULL,
	DEPARTMENTGROUPNAME VARCHAR(50) NULL
);


CREATE TABLE DIMEMPLOYEE(
	EMPLOYEEKEY INT PRIMARY KEY,
	PARENTEMPLOYEEKEY INT NULL,
	EMPLOYEENATIONALIDALTERNATEKEY VARCHAR(15) NULL,
	PARENTEMPLOYEENATIONALIDALTERNATEKEY VARCHAR(15) NULL,
	SALESTERRITORYKEY INT NULL,
	FIRSTNAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	MIDDLENAME VARCHAR(50) NULL,
	NAMESTYLE BOOLEAN NOT NULL,
	TITLE VARCHAR(50) NULL,
	HIREDATE DATE NULL,
	BIRTHDATE DATE NULL,
	LOGINID VARCHAR(256) NULL,
	EMAILADDRESS VARCHAR(50) NULL,
	PHONE VARCHAR(25) NULL,
	MARITALSTATUS CHAR(1) NULL,
	EMERGENCYCONTACTNAME VARCHAR(50) NULL,
	EMERGENCYCONTACTPHONE VARCHAR(25) NULL,
	SALARIEDFLAG BOOLEAN NULL,
	GENDER CHAR(1) NULL,
	PAYFREQUENCY TINYINT NULL,
	BASERATE DECIMAL(19,4) NULL,
	VACATIONHOURS SMALLINT NULL,
	SICKLEAVEHOURS SMALLINT NULL,
	CURRENTFLAG BOOLEAN NOT NULL,
	SALESPERSONFLAG BOOLEAN NOT NULL,
	DEPARTMENTNAME VARCHAR(50) NULL,
	STARTDATE DATE NULL,
	ENDDATE DATE NULL,
	STATUS VARCHAR(50) NULL,
	EMPLOYEEPHOTO VARBINARY NULL
);


CREATE TABLE DIMGEOGRAPHY(
	GEOGRAPHYKEY INT PRIMARY KEY,
	CITY VARCHAR(30) NULL,
	STATEPROVINCECODE VARCHAR(3) NULL,
	STATEPROVINCENAME VARCHAR(50) NULL,
	COUNTRYREGIONCODE VARCHAR(3) NULL,
	ENGLISHCOUNTRYREGIONNAME VARCHAR(50) NULL,
	SPANISHCOUNTRYREGIONNAME VARCHAR(50) NULL,
	FRENCHCOUNTRYREGIONNAME VARCHAR(50) NULL,
	POSTALCODE VARCHAR(15) NULL,
	SALESTERRITORYKEY INT NULL,
	IPADDRESSLOCATOR VARCHAR(15) NULL
);


CREATE TABLE DIMORGANIZATION(
	ORGANIZATIONKEY INT PRIMARY KEY,
	PARENTORGANIZATIONKEY INT NULL,
	PERCENTAGEOFOWNERSHIP VARCHAR(16) NULL,
	ORGANIZATIONNAME VARCHAR(50) NULL,
	CURRENCYKEY INT NULL
);


CREATE TABLE DIMPRODUCT(
	PRODUCTKEY INT PRIMARY KEY,
	PRODUCTALTERNATEKEY VARCHAR(25) NULL,
	PRODUCTSUBCATERYKEY INT NULL,
	WEIGHTUNITMEASURECODE CHAR(3) NULL,
	SIZEUNITMEASURECODE CHAR(3) NULL,
	ENGLISHPRODUCTNAME VARCHAR(50) NOT NULL,
	SPANISHPRODUCTNAME VARCHAR(50) NOT NULL,
	FRENCHPRODUCTNAME VARCHAR(50) NOT NULL,
	STANDARDCOST DECIMAL(19,4) NULL,
	FINISHEDODSFLAG BOOLEAN NOT NULL,
	COLOR VARCHAR(15) NOT NULL,
	SAFETYSTOCKLEVEL SMALLINT NULL,
	REORDERPOINT SMALLINT NULL,
	LISTPRICE DECIMAL(19,4) NULL,
	SIZE VARCHAR(50) NULL,
	SIZERANGE VARCHAR(50) NULL,
	WEIGHT FLOAT NULL,
	DAYSTOMANUFACTURE INT NULL,
	PRODUCTLINE CHAR(2) NULL,
	DEALERPRICE DECIMAL(19,4) NULL,
	CLASS CHAR(2) NULL,
	STYLE CHAR(2) NULL,
	MODELNAME VARCHAR(50) NULL,
	LARGEPHOTO VARBINARY NULL,
	ENGLISHDESCRIPTION VARCHAR(400) NULL,
	FRENCHDESCRIPTION VARCHAR(400) NULL,
	CHINESEDESCRIPTION VARCHAR(400) NULL,
	ARABICDESCRIPTION VARCHAR(400) NULL,
	HEBREWDESCRIPTION VARCHAR(400) NULL,
	THAIDESCRIPTION VARCHAR(400) NULL,
	GERMANDESCRIPTION VARCHAR(400) NULL,
	JAPANESEDESCRIPTION VARCHAR(400) NULL,
	TURKISHDESCRIPTION VARCHAR(400) NULL,
	STARTDATE DATETIME NULL,
	ENDDATE DATETIME NULL,
	STATUS VARCHAR(7) NULL
);


CREATE TABLE DIMPRODUCTCATEGORY(
	PRODUCTCATERYKEY INT PRIMARY KEY,
	PRODUCTCATERYALTERNATEKEY INT NULL,
	ENGLISHPRODUCTCATERYNAME VARCHAR(50) NOT NULL,
	SPANISHPRODUCTCATERYNAME VARCHAR(50) NOT NULL,
	FRENCHPRODUCTCATERYNAME VARCHAR(50) NOT NULL
);


CREATE TABLE DIMPRODUCTSUBCATEGORY(
	PRODUCTSUBCATERYKEY INT PRIMARY KEY,
	PRODUCTSUBCATERYALTERNATEKEY INT NULL,
	ENGLISHPRODUCTSUBCATERYNAME VARCHAR(50) NOT NULL,
	SPANISHPRODUCTSUBCATERYNAME VARCHAR(50) NOT NULL,
	FRENCHPRODUCTSUBCATERYNAME VARCHAR(50) NOT NULL,
	PRODUCTCATEGORYKEY INT NULL
);


CREATE TABLE DIMPROMOTION(
	PROMOTIONKEY INT PRIMARY KEY,
	PROMOTIONALTERNATEKEY INT NULL,
	ENGLISHPROMOTIONNAME VARCHAR(255) NULL,
	SPANISHPROMOTIONNAME VARCHAR(255) NULL,
	FRENCHPROMOTIONNAME VARCHAR(255) NULL,
	DISCOUNTPCT FLOAT NULL,
	ENGLISHPROMOTIONTYPE VARCHAR(50) NULL,
	SPANISHPROMOTIONTYPE VARCHAR(50) NULL,
	FRENCHPROMOTIONTYPE VARCHAR(50) NULL,
	ENGLISHPROMOTIONCATERY VARCHAR(50) NULL,
	SPANISHPROMOTIONCATERY VARCHAR(50) NULL,
	FRENCHPROMOTIONCATERY VARCHAR(50) NULL,
	STARTDATE DATETIME NOT NULL,
	ENDDATE DATETIME NULL,
	MINQTY INT NULL,
	MAXQTY INT NULL
);


CREATE TABLE DIMRESELLER(
	RESELLERKEY INT PRIMARY KEY,
	GEOGRAPHYKEY INT NULL,
	RESELLERALTERNATEKEY VARCHAR(15) NULL,
	PHONE VARCHAR(25) NULL,
	BUSINESSTYPE VARCHAR(20) NOT NULL,
	RESELLERNAME VARCHAR(50) NOT NULL,
	NUMBEREMPLOYEES INT NULL,
	ORDERFREQUENCY CHAR(1) NULL,
	ORDERMONTH TINYINT NULL,
	FIRSTORDERYEAR INT NULL,
	LASTORDERYEAR INT NULL,
	PRODUCTLINE VARCHAR(50) NULL,
	ADDRESSLINE1 VARCHAR(60) NULL,
	ADDRESSLINE2 VARCHAR(60) NULL,
	ANNUALSALES DECIMAL(19,4) NULL,
	BANKNAME VARCHAR(50) NULL,
	MINPAYMENTTYPE TINYINT NULL,
	MINPAYMENTAMOUNT DECIMAL(19,4) NULL,
	ANNUALREVENUE DECIMAL(19,4) NULL,
	YEAROPENED INT NULL
);


CREATE TABLE DIMSALESREASON(
	SALESREASONKEY INT PRIMARY KEY,
	SALESREASONALTERNATEKEY INT NOT NULL,
	SALESREASONNAME VARCHAR(50) NOT NULL,
	SALESREASONREASONTYPE VARCHAR(50) NOT NULL
);


CREATE TABLE DIMSALESTERRITORY(
	SALESTERRITORYKEY INT PRIMARY KEY,
	SALESTERRITORYALTERNATEKEY INT NULL,
	SALESTERRITORYREGION VARCHAR(50) NOT NULL,
	SALESTERRITORYCOUNTRY VARCHAR(50) NOT NULL,
	SALESTERRITORYGROUP VARCHAR(50) NULL,
	SALESTERRITORYIMAGE VARBINARY NULL
);


CREATE TABLE DIMSCENARIO(
	SCENARIOKEY INT PRIMARY KEY,
	SCENARIONAME VARCHAR(50) NULL
);


CREATE TABLE FACTADDITIONALINTERNATIONALPRODUCTDESCRIPTION(
	PRODUCTKEY INT NOT NULL,
	CULTURENAME VARCHAR(50) NOT NULL,
	PRODUCTDESCRIPTION VARCHAR(8000) NOT NULL
);


CREATE TABLE FACTCALLCENTER(
	FACTCALLCENTERID INT PRIMARY KEY,
	DATEKEY INT NOT NULL,
	WAGETYPE VARCHAR(15) NOT NULL,
	SHIFT VARCHAR(20) NOT NULL,
	LEVELONEOPERATORS SMALLINT NOT NULL,
	LEVELTWOOPERATORS SMALLINT NOT NULL,
	TOTALOPERATORS SMALLINT NOT NULL,
	CALLS INT NOT NULL,
	AUTOMATICRESPONSES INT NOT NULL,
	ORDERS INT NOT NULL,
	ISSUESRAISED SMALLINT NOT NULL,
	AVERAGETIMEPERISSUE SMALLINT NOT NULL,
	SERVICEGRADE FLOAT NOT NULL,
	DATE DATETIME NULL
);


CREATE TABLE FACTCURRENCYRATE(
	CURRENCYKEY INT NOT NULL,
	DATEKEY INT NOT NULL,
	AVERAGERATE FLOAT NOT NULL,
	ENDOFDAYRATE FLOAT NOT NULL,
	DATE DATETIME NULL
);


CREATE TABLE FACTFINANCE(
	FINANCEKEY INT PRIMARY KEY,
	DATEKEY INT NOT NULL,
	ORGANIZATIONKEY INT NOT NULL,
	DEPARTMENTGROUPKEY INT NOT NULL,
	SCENARIOKEY INT NOT NULL,
	ACCOUNTKEY INT NOT NULL,
	AMOUNT FLOAT NOT NULL,
	DATE DATETIME NULL
);


CREATE TABLE FACTINTERNETSALES(
	PRODUCTKEY INT NOT NULL,
	ORDERDATEKEY INT NOT NULL,
	DUEDATEKEY INT NOT NULL,
	SHIPDATEKEY INT NOT NULL,
	CUSTOMERKEY INT NOT NULL,
	PROMOTIONKEY INT NOT NULL,
	CURRENCYKEY INT NOT NULL,
	SALESTERRITORYKEY INT NOT NULL,
	SALESORDERNUMBER VARCHAR(20) NOT NULL,
	SALESORDERLINENUMBER TINYINT NOT NULL,
	REVISIONNUMBER TINYINT NOT NULL,
	ORDERQUANTITY SMALLINT NOT NULL,
	UNITPRICE DECIMAL(19,4) NOT NULL,
	EXTENDEDAMOUNT DECIMAL(19,4) NOT NULL,
	UNITPRICEDISCOUNTPCT FLOAT NOT NULL,
	DISCOUNTAMOUNT FLOAT NOT NULL,
	PRODUCTSTANDARDCOST DECIMAL(19,4) NOT NULL,
	TOTALPRODUCTCOST DECIMAL(19,4) NOT NULL,
	SALESAMOUNT DECIMAL(19,4) NOT NULL,
	TAXAMT DECIMAL(19,4) NOT NULL,
	FREIGHT DECIMAL(19,4) NOT NULL,
	CARRIERTRACKINGNUMBER VARCHAR(25) NULL,
	CUSTOMERPONUMBER VARCHAR(25) NULL,
	ORDERDATE DATETIME NULL,
	DUEDATE DATETIME NULL,
	SHIPDATE DATETIME NULL
);


CREATE TABLE FACTINTERNETSALESREASON(
	SALESORDERNUMBER VARCHAR(20) NOT NULL,
	SALESORDERLINENUMBER TINYINT NOT NULL,
	SALESREASONKEY INT NOT NULL
);


CREATE TABLE FACTPRODUCTINVENTORY(
	PRODUCTKEY INT NOT NULL,
	DATEKEY INT NOT NULL,
	MOVEMENTDATE DATE NOT NULL,
	UNITCOST DECIMAL(19,4) NOT NULL,
	UNITSIN INT NOT NULL,
	UNITSOUT INT NOT NULL,
	UNITSBALANCE INT NOT NULL
);


CREATE TABLE FACTRESELLERSALES(
	PRODUCTKEY INT NOT NULL,
	ORDERDATEKEY INT NOT NULL,
	DUEDATEKEY INT NOT NULL,
	SHIPDATEKEY INT NOT NULL,
	RESELLERKEY INT NOT NULL,
	EMPLOYEEKEY INT NOT NULL,
	PROMOTIONKEY INT NOT NULL,
	CURRENCYKEY INT NOT NULL,
	SALESTERRITORYKEY INT NOT NULL,
	SALESORDERNUMBER VARCHAR(20) NOT NULL,
	SALESORDERLINENUMBER TINYINT NOT NULL,
	REVISIONNUMBER TINYINT NULL,
	ORDERQUANTITY SMALLINT NULL,
	UNITPRICE DECIMAL(19,4) NULL,
	EXTENDEDAMOUNT DECIMAL(19,4) NULL,
	UNITPRICEDISCOUNTPCT FLOAT NULL,
	DISCOUNTAMOUNT FLOAT NULL,
	PRODUCTSTANDARDCOST DECIMAL(19,4) NULL,
	TOTALPRODUCTCOST DECIMAL(19,4) NULL,
	SALESAMOUNT DECIMAL(19,4) NULL,
	TAXAMT DECIMAL(19,4) NULL,
	FREIGHT DECIMAL(19,4) NULL,
	CARRIERTRACKINGNUMBER VARCHAR(25) NULL,
	CUSTOMERPONUMBER VARCHAR(25) NULL,
	ORDERDATE DATETIME NULL,
	DUEDATE DATETIME NULL,
	SHIPDATE DATETIME NULL
);


CREATE TABLE FACTSALESQUOTA(
	SALESQUOTAKEY INT PRIMARY KEY,
	EMPLOYEEKEY INT NOT NULL,
	DATEKEY INT NOT NULL,
	CALENDARYEAR SMALLINT NOT NULL,
	CALENDARQUARTER TINYINT NOT NULL,
	SALESAMOUNTQUOTA DECIMAL(19,4) NOT NULL,
	DATE DATETIME NULL
);


CREATE TABLE FACTSURVEYRESPONSE(
	SURVEYRESPONSEKEY INT PRIMARY KEY,
	DATEKEY INT NOT NULL,
	CUSTOMERKEY INT NOT NULL,
	PRODUCTCATERYKEY INT NOT NULL,
	ENGLISHPRODUCTCATERYNAME VARCHAR(50) NOT NULL,
	PRODUCTSUBCATERYKEY INT NOT NULL,
	ENGLISHPRODUCTSUBCATERYNAME VARCHAR(50) NOT NULL,
	DATE DATETIME NULL
);


CREATE TABLE NEWFACTCURRENCYRATE(
	AVERAGERATE REAL NULL,
	CURRENCYID VARCHAR(3) NULL,
	CURRENCYDATE DATE NULL,
	ENDOFDAYRATE REAL NULL,
	CURRENCYKEY INT NULL,
	DATEKEY INT NULL
);


CREATE TABLE PROSPECTIVEBUYER(
	PROSPECTIVEBUYERKEY INT PRIMARY KEY,
	PROSPECTALTERNATEKEY VARCHAR(15) NULL,
	FIRSTNAME VARCHAR(50) NULL,
	MIDDLENAME VARCHAR(50) NULL,
	LASTNAME VARCHAR(50) NULL,
	BIRTHDATE DATETIME NULL,
	MARITALSTATUS CHAR(1) NULL,
	GENDER VARCHAR(1) NULL,
	EMAILADDRESS VARCHAR(50) NULL,
	YEARLYINCOME DECIMAL(19,4) NULL,
	TOTALCHILDREN TINYINT NULL,
	NUMBERCHILDRENATHOME TINYINT NULL,
	EDUCATION VARCHAR(40) NULL,
	OCCUPATION VARCHAR(100) NULL,
	HOUSEOWNERFLAG CHAR(1) NULL,
	NUMBERCARSOWNED TINYINT NULL,
	ADDRESSLINE1 VARCHAR(120) NULL,
	ADDRESSLINE2 VARCHAR(120) NULL,
	CITY VARCHAR(30) NULL,
	STATEPROVINCECODE VARCHAR(3) NULL,
	POSTALCODE VARCHAR(15) NULL,
	PHONE VARCHAR(20) NULL,
	SALUTATION VARCHAR(8) NULL,
	UNKNOWN INT NULL
);